version: "3.8"

x-postgres-environment: &x-postgres-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_NAME: ${POSTGRES_NAME}

x-redis-environment: &x-redis-environment
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  REDIS_HOST: ${REDIS_HOST}
  REDIS_DATABASE: ${REDIS_DATABASE}

services:
  database:
    restart: always
    image: postgres:alpine
    environment:
      <<: *x-postgres-environment
    volumes:
      - pgdata:/var/gpt_gpb/data
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      basic:

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      basic:

  backend:
    tty: true
    restart: always
    build: backend
    ports:
      - "10526:8000"
    environment:
      <<: *x-redis-environment
      <<: *x-postgres-environment
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - database
      - redis
    networks:
      basic:
volumes:
  pgdata:

networks:
  basic:
    driver: bridge