# Generated by Django 4.2 on 2023-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=8000)),
                ('role', models.BooleanField(default=False)),
                ('session_id', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
