# Generated by Django 4.2 on 2023-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500, null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
